<a href="https://colab.research.google.com/github/Aravinda89/Pytorch-Tutorial/blob/main/Autograd_with_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd with tensors

In [1]:
import torch

In [2]:
w = torch.randn(4, 3, requires_grad=True)

In [3]:
w

tensor([[ 0.4569, -0.3766, -0.5346],
        [ 0.5358, -0.5115,  0.0576],
        [-1.5081, -0.6145, -0.6205],
        [-0.3985,  0.3321,  1.0358]], requires_grad=True)

In [4]:
w.requires_grad_(False)

tensor([[ 0.4569, -0.3766, -0.5346],
        [ 0.5358, -0.5115,  0.0576],
        [-1.5081, -0.6145, -0.6205],
        [-0.3985,  0.3321,  1.0358]])

In [5]:
w.requires_grad_(True)

tensor([[ 0.4569, -0.3766, -0.5346],
        [ 0.5358, -0.5115,  0.0576],
        [-1.5081, -0.6145, -0.6205],
        [-0.3985,  0.3321,  1.0358]], requires_grad=True)

In [7]:
y = torch.exp(w)
y

tensor([[1.5792, 0.6862, 0.5859],
        [1.7089, 0.5996, 1.0593],
        [0.2213, 0.5409, 0.5377],
        [0.6713, 1.3939, 2.8173]], grad_fn=<ExpBackward>)

In [10]:
y.grad_fn

In [11]:
outp = y.mean()
outp

tensor(1.0335, grad_fn=<MeanBackward0>)

In [14]:
print(w.grad)

None


In [15]:
outp.backward()

In [16]:
print(w.grad)

tensor([[0.1316, 0.0572, 0.0488],
        [0.1424, 0.0500, 0.0883],
        [0.0184, 0.0451, 0.0448],
        [0.0559, 0.1162, 0.2348]])


In [17]:
print(w.detach())

tensor([[ 0.4569, -0.3766, -0.5346],
        [ 0.5358, -0.5115,  0.0576],
        [-1.5081, -0.6145, -0.6205],
        [-0.3985,  0.3321,  1.0358]])


In [18]:
print(outp.requires_grad)

True


In [19]:
with torch.no_grad():
  outp = (w+y).mean()

print(outp.requires_grad)

False
