<a href="https://colab.research.google.com/github/Aravinda89/Pytorch-Tutorial/blob/main/Tensors_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors 

In [3]:
import torch

## zeros()

In [6]:
w = torch.zeros(4,3)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [7]:
w.size()

torch.Size([4, 3])

In [9]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [10]:
w = torch.randn(4,3)
w

tensor([[ 0.8116, -0.0175,  1.2624],
        [-0.4721,  0.1315,  1.0744],
        [-0.0382, -0.9796, -0.8987],
        [ 0.3137, -0.2732, -1.7904]])

In [11]:
t = torch.rand_like(w)
t

tensor([[0.6517, 0.9168, 0.1794],
        [0.3799, 0.6326, 0.2029],
        [0.7190, 0.9403, 0.3736],
        [0.4728, 0.6704, 0.4142]])

## fill_()

In [12]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [13]:
t = w.view(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
w.view(3,-1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [15]:
w

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
w.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [19]:
type(w.numpy())

numpy.ndarray