<a href="https://colab.research.google.com/github/Aravinda89/Pytorch-Tutorial/blob/main/Using_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd with tensors

In [1]:
import torch

In [2]:
w = torch.randn(4,3,requires_grad=True)

In [3]:
w

tensor([[-0.1357,  0.0642, -0.1551],
        [-1.6032, -0.4025,  0.1917],
        [ 1.1057, -0.4362,  0.6599],
        [ 2.3116,  1.5459, -1.0386]], requires_grad=True)

In [4]:
w.requires_grad_(False)

tensor([[-0.1357,  0.0642, -0.1551],
        [-1.6032, -0.4025,  0.1917],
        [ 1.1057, -0.4362,  0.6599],
        [ 2.3116,  1.5459, -1.0386]])

In [5]:
w.requires_grad_(True)

tensor([[-0.1357,  0.0642, -0.1551],
        [-1.6032, -0.4025,  0.1917],
        [ 1.1057, -0.4362,  0.6599],
        [ 2.3116,  1.5459, -1.0386]], requires_grad=True)

In [7]:
y =  torch.exp(w)
y

tensor([[ 0.8731,  1.0663,  0.8563],
        [ 0.2012,  0.6686,  1.2112],
        [ 3.0214,  0.6465,  1.9345],
        [10.0909,  4.6920,  0.3540]], grad_fn=<ExpBackward>)

In [8]:
y.grad_fn

In [9]:
output = y.mean()
output

tensor(2.1347, grad_fn=<MeanBackward0>)

In [10]:
print(w.grad)

None


In [11]:
output.backward()

In [12]:
print(w.grad)

tensor([[0.0728, 0.0889, 0.0714],
        [0.0168, 0.0557, 0.1009],
        [0.2518, 0.0539, 0.1612],
        [0.8409, 0.3910, 0.0295]])


In [13]:
print(output.requires_grad)

True


In [14]:
with torch.no_grad():
  output = (w+y).mean()

print(output.requires_grad)

False
